# Generated by Django 3.2 on 2022-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_validated',
            field=models.BooleanField(default=False),
        ),
    ]
