# Generated by Django 3.2 on 2022-09-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_requestednewphonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestednewphonenumber',
            old_name='sent_on',
            new_name='created_on',
        ),
    ]
