# Generated by Django 3.2 on 2022-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220922_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestednewphonenumber',
            name='validated',
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['receiver'], name='users_otp_receive_a8d200_idx'),
        ),
        migrations.AddIndex(
            model_name='requestednewphonenumber',
            index=models.Index(fields=['user', 'phone_number'], name='users_reque_user_id_650b0c_idx'),
        ),
    ]
