# Generated by Django 3.2 on 2022-10-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptionplansg', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(verbose_name='transaction date')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptionplansg.plancost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_transaction', 'user'),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_billing_start', models.DateTimeField(blank=True, null=True, verbose_name='billing start date')),
                ('date_billing_end', models.DateTimeField(blank=True, null=True, verbose_name='billing start end')),
                ('date_billing_last', models.DateTimeField(blank=True, null=True, verbose_name='last billing date')),
                ('date_billing_next', models.DateTimeField(blank=True, null=True, verbose_name='next start date')),
                ('active', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptionplansg.plancost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'date_billing_start'),
            },
        ),
        migrations.DeleteModel(
            name='businessPlan',
        ),
    ]
