# Generated by Django 3.2 on 2022-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20220917_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
