# Generated by Django 3.2 on 2022-10-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20221024_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='teant_attched',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_subscriptions', to='tenant.tenant'),
        ),
    ]
