# Generated by Django 3.2 on 2022-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
