# Generated by Django 3.2 on 2022-10-27 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_alter_tenantsubscription_date_billing_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='date_billing_last',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='date_billing_next',
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 21, 1, 38, 541187), null=True, verbose_name='billing start date'),
        ),
    ]
