# Generated by Django 3.2 on 2022-10-27 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20221027_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='active',
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 21, 17, 53, 673818), null=True, verbose_name='billing start date'),
        ),
    ]
