# Generated by Django 3.2 on 2022-10-27 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20221027_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='teant_attched',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_subscriptions_transection', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 23, 52, 59, 302566), null=True, verbose_name='billing start date'),
        ),
    ]
