# Generated by Django 3.2 on 2022-10-27 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20221027_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 0, 1, 14, 527533), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 0, 1, 14, 526959), null=True, verbose_name='billing start date'),
        ),
    ]
