# Generated by Django 3.2 on 2022-10-27 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20221028_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 1, 2, 57, 431984), null=True, verbose_name='start date')),
                ('paid_template', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 1, 2, 57, 433012), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 1, 2, 57, 432588), null=True, verbose_name='billing start date'),
        ),
        migrations.CreateModel(
            name='TenantTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 1, 2, 57, 432262), null=True, verbose_name='start date')),
                ('paid_template', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('teant_attched', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_template', to='tenant.tenant')),
            ],
        ),
    ]
