# Generated by Django 3.2 on 2022-10-27 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_auto_20221028_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanttemplate',
            name='templates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_attached_template', to='tenant.alltemplate'),
        ),
        migrations.AlterField(
            model_name='alltemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 1, 6, 21, 658671), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 1, 6, 21, 659932), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 1, 6, 21, 659447), null=True, verbose_name='billing start date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='teant_attched',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_subscriptions', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 1, 6, 21, 659038), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='teant_attched',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_template', to='tenant.tenant'),
        ),
    ]
