# Generated by Django 3.2 on 2022-10-28 18:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_auto_20221029_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenanttemplate',
            name='template_code',
        ),
        migrations.AddField(
            model_name='alltemplate',
            name='template_code',
            field=models.CharField(default=123456, max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alltemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 0, 9, 28, 61372), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 0, 9, 28, 62487), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 0, 9, 28, 62043), null=True, verbose_name='billing start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 0, 9, 28, 61680), null=True, verbose_name='start date'),
        ),
    ]
