# Generated by Django 3.2 on 2022-10-30 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0015_auto_20221029_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 59, 19, 74785), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 15, 59, 19, 76141), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 59, 19, 75601), null=True, verbose_name='billing start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 59, 19, 75150), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='templates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_attached_template', to='tenant.alltemplate'),
        ),
    ]
