# Generated by Django 3.2 on 2022-11-01 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0021_auto_20221101_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(default=datetime.datetime(2022, 11, 1, 22, 20, 55, 445710), verbose_name='transaction date')),
                ('total_otp_cradit', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('teant_attched', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teant_otp', to='tenant.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_transaction', 'user'),
            },
        ),
        migrations.AlterField(
            model_name='alltemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 22, 20, 55, 443861), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 22, 20, 55, 445232), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 22, 20, 55, 444686), null=True, verbose_name='billing start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 22, 20, 55, 444231), null=True, verbose_name='start date'),
        ),
        migrations.DeleteModel(
            name='OTPwallet',
        ),
    ]
