# Generated by Django 3.2 on 2023-01-01 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_auto_20221224_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanttemplate',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='bannerimages/'),
        ),
        migrations.AlterField(
            model_name='alltemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 1, 22, 50, 11, 563434), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='otpwallet',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 22, 50, 11, 565606), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 22, 50, 11, 564935), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 1, 22, 50, 11, 564424), null=True, verbose_name='billing start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 1, 22, 50, 11, 563895), null=True, verbose_name='start date'),
        ),
    ]
