# Generated by Django 3.2 on 2023-01-27 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0037_auto_20230106_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 0, 30, 53, 102840), null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='otpwallet',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 0, 30, 53, 104549), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 0, 30, 53, 104133), verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 0, 30, 53, 103690), null=True, verbose_name='billing start date'),
        ),
        migrations.AlterField(
            model_name='tenanttemplate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 0, 30, 53, 103170), null=True, verbose_name='start date'),
        ),
    ]
