# Generated by Django 3.2 on 2022-10-24 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=128)),
                ('plan_description', models.CharField(blank=True, max_length=512, null=True)),
                ('grace_period', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='plans', to='subscriptionplansg.PlanTag')),
            ],
            options={
                'ordering': ('plan_name',),
                'permissions': (('subscriptions', 'Can interact with subscription details'),),
            },
        ),
        migrations.CreateModel(
            name='PlanListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, null=True)),
                ('subscribe_button_text', models.CharField(blank=True, default='Subscribe', max_length=128, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_list_details', to='subscriptionplansg.subscriptionplan')),
                ('plan_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_list_details', to='subscriptionplansg.planlist')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('recurrence_period', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('recurrence_unit', models.CharField(choices=[('0', 'once'), ('1', 'second'), ('2', 'minute'), ('3', 'hour'), ('4', 'day'), ('5', 'week'), ('6', 'month'), ('7', 'year')], default='6', max_length=1)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='subscriptionplansg.subscriptionplan')),
            ],
            options={
                'ordering': ('recurrence_unit', 'recurrence_period', 'cost'),
            },
        ),
    ]
