# Generated by Django 3.2 on 2023-01-29 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(max_length=100)),
                ('additional_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.IntegerField()),
                ('carousel_img', models.ImageField(upload_to='Carousel_Image')),
                ('select_type', models.CharField(blank=True, choices=[('static', 'static'), ('link', 'link'), ('package', 'package'), ('category', 'category')], default='static', max_length=100, null=True)),
                ('select_type_ids', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('validity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(upload_to='Category_Icon')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('package_stages', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=100, null=True)),
                ('payment_stages', models.CharField(blank=True, max_length=100, null=True)),
                ('price_paid', models.FloatField(default=0)),
                ('refund', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='package_Icons')),
                ('package_name', models.CharField(max_length=100)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('offering_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('total_time', models.CharField(max_length=100, null=True)),
                ('offer', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_package', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=100)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('offering_price', models.FloatField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_variants', to='main.package')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.TextField(blank=True, default=' ', null=True)),
                ('street', models.TextField(default=' ')),
                ('city', models.TextField(default=' ')),
                ('postal_code', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('state', models.TextField(default='')),
                ('address_type', models.CharField(blank=True, choices=[('Others', 'Others'), ('Home', 'Home')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_useraddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ManyToManyField(blank=True, null=True, related_name='addon_packagecheckout', to='main.AddOns')),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_packagecheckout', to='main.checkout')),
                ('packages', models.ManyToManyField(blank=True, null=True, related_name='packages_packagescheckout', to='main.Package')),
                ('variants', models.ManyToManyField(blank=True, null=True, related_name='variants_packagecheckouts', to='main.Variants')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='price_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricetag_package', to='main.pricetag'),
        ),
        migrations.CreateModel(
            name='DiscountedCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_coupon_type', models.CharField(blank=True, choices=[('percentage_discount', 'percentage_discount'), ('flat_discount', 'flat_discount')], default='static', max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_code', models.CharField(max_length=30)),
                ('flat_percent_value', models.FloatField(blank=True, null=True)),
                ('uses_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_order_value', models.FloatField()),
                ('maximum_order_value', models.FloatField(blank=True, null=True)),
                ('apply_coupon_on', models.CharField(blank=True, choices=[('category', 'category'), ('package', 'package'), ('all', 'all')], default='all', max_length=100, null=True)),
                ('show_coupons_to_customer', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='categories_discountcoupons', to='main.Category')),
                ('packages', models.ManyToManyField(blank=True, null=True, related_name='package_discountcoupons', to='main.Package')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_checkout', to='main.discountedcoupons'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addons',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_addons', to='main.package'),
        ),
    ]
