# Generated by Django 3.2 on 2023-02-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
