# Generated by Django 3.2 on 2023-02-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_packagecheckout_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecheckout',
            name='packages',
        ),
        migrations.AddField(
            model_name='packagecheckout',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_packagescheckout', to='main.package'),
        ),
        migrations.RemoveField(
            model_name='packagecheckout',
            name='variants',
        ),
        migrations.AddField(
            model_name='packagecheckout',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_packagecheckouts', to='main.variants'),
        ),
    ]
